-- DROP DATABASE TailorManagementDB
IF NOT EXISTS (SELECT 1 FROM sys.databases WHERE name = 'TailorManagementDB')
BEGIN
	CREATE DATABASE TailorManagementDB;
END
GO

USE TailorManagementDB
GO

IF OBJECT_ID('dbo.tbPant', 'U') IS NULL 
BEGIN
	CREATE TABLE tbPant (
		Id INT IDENTITY(1,1) PRIMARY KEY,
		[Length1] NVARCHAR(10), [Length2] NVARCHAR(10), [Length3] NVARCHAR(10), [Length4] NVARCHAR(10), [Length5] NVARCHAR(10),
		[Kamar1] NVARCHAR(10), [Kamar2] NVARCHAR(10), [Kamar3] NVARCHAR(10), [Kamar4] NVARCHAR(10), [Kamar5] NVARCHAR(10),
		[Seat1] NVARCHAR(10), [Seat2] NVARCHAR(10), [Seat3] NVARCHAR(10), [Seat4] NVARCHAR(10), [Seat5] NVARCHAR(10),
		[Jangh1] NVARCHAR(10), [Jangh2] NVARCHAR(10), [Jangh3] NVARCHAR(10), [Jangh4] NVARCHAR(10), [Jangh5] NVARCHAR(10),
		[Gothan1] NVARCHAR(10), [Gothan2] NVARCHAR(10), [Gothan3] NVARCHAR(10), [Gothan4] NVARCHAR(10), [Gothan5] NVARCHAR(10),
		[Jolo1] NVARCHAR(10), [Jolo2] NVARCHAR(10), [Jolo3] NVARCHAR(10), [Jolo4] NVARCHAR(10), [Jolo5] NVARCHAR(10),
		[Moli1] NVARCHAR(10), [Moli2] NVARCHAR(10), [Moli3] NVARCHAR(10), [Moli4] NVARCHAR(10), [Moli5] NVARCHAR(10),
		Notes NVARCHAR(MAX)
	)
END
GO

IF OBJECT_ID('dbo.tbShirt', 'U') IS NULL 
BEGIN
	CREATE TABLE tbShirt (
		Id INT IDENTITY(1,1) PRIMARY KEY,
		[Length1] NVARCHAR(10), [Length2] NVARCHAR(10), [Length3] NVARCHAR(10), [Length4] NVARCHAR(10), [Length5] NVARCHAR(10),
		[Chati1] NVARCHAR(10), [Chati2] NVARCHAR(10), [Chati3] NVARCHAR(10), [Chati4] NVARCHAR(10), [Chati5] NVARCHAR(10),
		[Solder1] NVARCHAR(10), [Solder2] NVARCHAR(10), [Solder3] NVARCHAR(10), [Solder4] NVARCHAR(10), [Solder5] NVARCHAR(10),
		[Bye1] NVARCHAR(10), [Bye2] NVARCHAR(10), [Bye3] NVARCHAR(10), [Bye4] NVARCHAR(10), [Bye5] NVARCHAR(10),
		[Front1] NVARCHAR(10), [Front2] NVARCHAR(10), [Front3] NVARCHAR(10), [Front4] NVARCHAR(10), [Front5] NVARCHAR(10),
		[Kolor1] NVARCHAR(10), [Kolor2] NVARCHAR(10), [Kolor3] NVARCHAR(10), [Kolor4] NVARCHAR(10), [Kolor5] NVARCHAR(10),
		[Cuff1] NVARCHAR(10), [Cuff2] NVARCHAR(10), [Cuff3] NVARCHAR(10), [Cuff4] NVARCHAR(10), [Cuff5] NVARCHAR(10),
		Notes NVARCHAR(MAX)
	)
END
GO

IF OBJECT_ID('dbo.tbCustomer', 'U') IS NULL 
BEGIN
	CREATE TABLE tbCustomer (
		Id INT IDENTITY(1,1) PRIMARY KEY,
		[Name] NVARCHAR(100),
		Mobile NVARCHAR(10)
	)
END
GO

IF OBJECT_ID('dbo.tbMenu', 'U') IS NULL 
BEGIN
	CREATE TABLE tbMenu (
		Id INT IDENTITY(1,1) PRIMARY KEY,
		[Name] NVARCHAR(100),
		Price DECIMAL(18, 2)
	)
END
GO

IF OBJECT_ID('dbo.tbBill', 'U') IS NULL 
BEGIN
	CREATE TABLE tbBill (
		Id INT IDENTITY(1,1) PRIMARY KEY,
		[CustomerId] INT FOREIGN KEY  REFERENCES tbCustomer(Id),
		BillNo INT,
		BillDate DATETIME,
		DeliveryDate DATETIME,
		TrialDate DATETIME,		
		ExtraCost DECIMAL(18,2),
		TotalAmount DECIMAL(18,2),
		PaidAmount DECIMAL(18,2),
		DueAmount AS (TotalAmount - PaidAmount)
	)
END
GO

IF OBJECT_ID('dbo.tbBillDetail', 'U') IS NULL 
BEGIN
	CREATE TABLE tbBillDetail (
		Id INT IDENTITY(1,1) PRIMARY KEY,
		[BillId] INT FOREIGN KEY  REFERENCES tbBill(Id),
		MenuId INT FOREIGN KEY  REFERENCES tbMenu(Id),
		Qty DECIMAL(18,2),
		Price DECIMAL(18,2),
		Total DECIMAL(18,2)
	)
END
GO
