//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TailorManagement1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TailorManagement1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btncancel {
            get {
                return ResourceManager.GetString("btncancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btndelete {
            get {
                return ResourceManager.GetString("btndelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string btnexit {
            get {
                return ResourceManager.GetString("btnexit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string btnlogin {
            get {
                return ResourceManager.GetString("btnlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        public static string btnnew {
            get {
                return ResourceManager.GetString("btnnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre&amp;view.
        /// </summary>
        public static string btnpreview {
            get {
                return ResourceManager.GetString("btnpreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Print.
        /// </summary>
        public static string btnprint {
            get {
                return ResourceManager.GetString("btnprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive Amount.
        /// </summary>
        public static string btnreceiveamount {
            get {
                return ResourceManager.GetString("btnreceiveamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        public static string btnsave {
            get {
                return ResourceManager.GetString("btnsave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Print.
        /// </summary>
        public static string btnsaveandprint {
            get {
                return ResourceManager.GetString("btnsaveandprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance.
        /// </summary>
        public static string lbladvance {
            get {
                return ResourceManager.GetString("lbladvance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Date.
        /// </summary>
        public static string lblbilldate {
            get {
                return ResourceManager.GetString("lblbilldate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BillNo.
        /// </summary>
        public static string lblbillno {
            get {
                return ResourceManager.GetString("lblbillno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye.
        /// </summary>
        public static string lblbye {
            get {
                return ResourceManager.GetString("lblbye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chati.
        /// </summary>
        public static string lblchati {
            get {
                return ResourceManager.GetString("lblchati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Address.
        /// </summary>
        public static string lblcompanyaddress {
            get {
                return ResourceManager.GetString("lblcompanyaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Mobile.
        /// </summary>
        public static string lblcompanymobile {
            get {
                return ResourceManager.GetString("lblcompanymobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string lblcompanyname {
            get {
                return ResourceManager.GetString("lblcompanyname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuff.
        /// </summary>
        public static string lblcuff {
            get {
                return ResourceManager.GetString("lblcuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del. Date.
        /// </summary>
        public static string lbldeliverydate {
            get {
                return ResourceManager.GetString("lbldeliverydate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Days.
        /// </summary>
        public static string lbldeliverydays {
            get {
                return ResourceManager.GetString("lbldeliverydays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Due.
        /// </summary>
        public static string lbldeliverydue {
            get {
                return ResourceManager.GetString("lbldeliverydue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lbldescription {
            get {
                return ResourceManager.GetString("lbldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string lbldiscount {
            get {
                return ResourceManager.GetString("lbldiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due.
        /// </summary>
        public static string lbldue {
            get {
                return ResourceManager.GetString("lbldue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Amount.
        /// </summary>
        public static string lbldueamount {
            get {
                return ResourceManager.GetString("lbldueamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Cost.
        /// </summary>
        public static string lblextracost {
            get {
                return ResourceManager.GetString("lblextracost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front.
        /// </summary>
        public static string lblfront {
            get {
                return ResourceManager.GetString("lblfront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gothan.
        /// </summary>
        public static string lblgothan {
            get {
                return ResourceManager.GetString("lblgothan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jangh.
        /// </summary>
        public static string lbljangh {
            get {
                return ResourceManager.GetString("lbljangh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jolo.
        /// </summary>
        public static string lbljolo {
            get {
                return ResourceManager.GetString("lbljolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kamar.
        /// </summary>
        public static string lblkamar {
            get {
                return ResourceManager.GetString("lblkamar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolor.
        /// </summary>
        public static string lblkolor {
            get {
                return ResourceManager.GetString("lblkolor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lbllanguage {
            get {
                return ResourceManager.GetString("lbllanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Description.
        /// </summary>
        public static string lbllocaldescription {
            get {
                return ResourceManager.GetString("lbllocaldescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string lblmobile {
            get {
                return ResourceManager.GetString("lblmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moli.
        /// </summary>
        public static string lblmoli {
            get {
                return ResourceManager.GetString("lblmoli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lblname {
            get {
                return ResourceManager.GetString("lblname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner Name.
        /// </summary>
        public static string lblownername {
            get {
                return ResourceManager.GetString("lblownername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string lblpaidamount {
            get {
                return ResourceManager.GetString("lblpaidamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pant.
        /// </summary>
        public static string lblpant {
            get {
                return ResourceManager.GetString("lblpant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambai.
        /// </summary>
        public static string lblpantlambai {
            get {
                return ResourceManager.GetString("lblpantlambai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblpantnotes {
            get {
                return ResourceManager.GetString("lblpantnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pant Price.
        /// </summary>
        public static string lblpantprice {
            get {
                return ResourceManager.GetString("lblpantprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pant Qty.
        /// </summary>
        public static string lblpantqty {
            get {
                return ResourceManager.GetString("lblpantqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lblpassword {
            get {
                return ResourceManager.GetString("lblpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Due.
        /// </summary>
        public static string lblpaymentdue {
            get {
                return ResourceManager.GetString("lblpaymentdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string lblqty {
            get {
                return ResourceManager.GetString("lblqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string lblrate {
            get {
                return ResourceManager.GetString("lblrate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seat.
        /// </summary>
        public static string lblseat {
            get {
                return ResourceManager.GetString("lblseat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt.
        /// </summary>
        public static string lblshirt {
            get {
                return ResourceManager.GetString("lblshirt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lambai.
        /// </summary>
        public static string lblshirtlambai {
            get {
                return ResourceManager.GetString("lblshirtlambai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblshirtnotes {
            get {
                return ResourceManager.GetString("lblshirtnotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt Price.
        /// </summary>
        public static string lblshirtprice {
            get {
                return ResourceManager.GetString("lblshirtprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shirt Qty.
        /// </summary>
        public static string lblshirtqty {
            get {
                return ResourceManager.GetString("lblshirtqty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solder.
        /// </summary>
        public static string lblsolder {
            get {
                return ResourceManager.GetString("lblsolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string lbltotal {
            get {
                return ResourceManager.GetString("lbltotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Amount.
        /// </summary>
        public static string lbltotalamount {
            get {
                return ResourceManager.GetString("lbltotalamount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Date.
        /// </summary>
        public static string lbltrialdate {
            get {
                return ResourceManager.GetString("lbltrialdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Days.
        /// </summary>
        public static string lbltrialdays {
            get {
                return ResourceManager.GetString("lbltrialdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string lbluserid {
            get {
                return ResourceManager.GetString("lbluserid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vigat.
        /// </summary>
        public static string lblvigat {
            get {
                return ResourceManager.GetString("lblvigat", resourceCulture);
            }
        }
    }
}
